import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "washed-light-green-50": "#e6f9e6",
        "washed-light-green-100": "#b2f0b2",
        "washed-light-green-200": "#8ce68c",
        "washed-light-green-300": "#66dd66",
        "washed-light-green-400": "#4dd54d",
        "washed-light-green-500": "#33cc33",
        "washed-light-green-600": "#2bb32b",
        "washed-light-green-700": "#239923",
        "washed-light-green-800": "#1a801a",
        "washed-light-green-900": "#146614",
        "washed-dark-green-50": "#e6ffe6",
        "washed-dark-green-100": "#b2ffb2",
        "washed-dark-green-200": "#8cff8c",
        "washed-dark-green-300": "#66ff66",
        "washed-dark-green-400": "#4dff4d",
        "washed-dark-green-500": "#33ff33",
        "washed-dark-green-600": "#2be82b",
        "washed-dark-green-700": "#23b523",
        "washed-dark-green-800": "#1a8c1a",
        "washed-dark-green-900": "#146b14",
        "primary-light-green-50": "#e6ffe6",
        "primary-light-green-100": "#b2ffb2",
        "primary-light-green-200": "#8cff8c",
        "primary-light-green-300": "#66ff66",
        "primary-light-green-400": "#4dff4d",
        "primary-light-green-500": "#33ff33",
        "primary-light-green-600": "#2be82b",
        "primary-light-green-700": "#23b523",
        "primary-light-green-800": "#1a8c1a",
        "primary-light-green-900": "#146b14",
        "primary-dark-green-50": "#e6ffe6",
        "primary-dark-green-100": "#b2ffb2",
        "primary-dark-green-200": "#8cff8c",
        "primary-dark-green-300": "#66ff66",
        "primary-dark-green-400": "#4dff4d",
        "primary-dark-green-500": "#33ff33",
        "primary-dark-green-600": "#2be82b",
        "primary-dark-green-700": "#23b523",
        "primary-dark-green-800": "#1a8c1a",
        "primary-dark-green-900": "#146b14",
        "Neutrals/neutrals-1": "#ffffff",
        "Neutrals/neutrals-2": "#fcfcfd",
        "Neutrals/neutrals-3": "#f5f5f6",
        "Neutrals/neutrals-4": "#f0f0f1",
        "Neutrals/neutrals-5": "#d9d9dc",
        "Neutrals/neutrals-6": "#c0bfc4",
        "Neutrals/neutrals-7": "#8d8c95",
        "Neutrals/neutrals-8": "#5b5966",
        "Neutrals/neutrals-9": "#464553",
        "Neutrals/neutrals-10": "#282637",
        "Neutrals/neutrals-11": "#201f30",
        "Neutrals/neutrals-12": "#161427",
        "Neutrals/neutrals-13": "#020014",
        "brand-washedLightGreen": "#33cc33",
        "brand-washedDarkGreen": "#66ff66",
        "brand-primaryLightGreen": "#2be82b",
        "brand-primaryDarkGreen": "#146b14",
        "brand-dark": "#030014",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
